using Discord;
using Discord.WebSocket;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AquaBot
{
    public static class DrinkingHandler
    {
        public static Random DrinkingRandom = new Random();

        public static async Task SetDrinkers(SocketMessage message, Settings settings, Func<LogMessage, Task> log)
        {
            await log(new LogMessage(LogSeverity.Info, "Discord", $"{message.Content.ToLower()} detected, setting drinkers"));

            var mentions = message.MentionedUsers;
            if (mentions.Count > 0)
            {
                settings.CurrentSettings.Drinkers = mentions.Select(x => x.Id).ToArray();
                settings.SaveSettings();
            }

            await message.Channel.SendMessageAsync($"Drinkers set, kampai!");
        }

        public static async Task Drink(SocketMessage message, Settings settings, DiscordSocketClient client, Func<LogMessage, Task> log)
        {
            await log(new LogMessage(LogSeverity.Info, "Discord", $"{message.Content.ToLower()} detected, finding a drinker"));

            var drinkers = settings.CurrentSettings.Drinkers;

            if(drinkers.Count() <= 0)
            {
                await message.Channel.SendMessageAsync($"No users in the drinking crew, set the crew with !drinkers ");
                return;
            }

            var roll = DrinkingRandom.Next(0, drinkers.Length);
            var user = client.GetUser(drinkers[roll]);

            if (user == null)
            {
                await message.Channel.SendMessageAsync($"Could not find user in the drinking crew :( ");
                return;
            }

            roll = DrinkingRandom.Next(0, Insults.Count);
            var insult = Insults[roll];

            await message.Channel.SendMessageAsync($"Drinky time { user.Mention } you {insult}");
            await RandomImageHandler.AquaKanpai(message, log, false);
        }

        private static readonly List<string> Insults = new List<string>()
        {
    "Amateur                    ",
    "Animal                     ",
    "Anorak                     ",
    "Ape                        ",
    "Apefucker                  ",
    "Apeshit                    ",
    "Arse                       ",
    "Arse-licker                ",
    "Arsebreath                 ",
    "Arsecunt                   ",
    "Arseface                   ",
    "Arsehole                   ",
    "Ass                        ",
    "Ass-face                   ",
    "Ass-kisser                 ",
    "Ass-nugget                 ",
    "Ass clown                  ",
    "Asscunt                    ",
    "Assface                    ",
    "Asshat                     ",
    "Asshole                    ",
    "Assmonkey                  ",
    "Assmunch                   ",
    "Asswagon                   ",
    "Assweed                    ",
    "Asswipe                    ",
    "Aunt fucker                ",
    "Baby                       ",
    "Backwoodsman               ",
    "Badass                     ",
    "Badgerfucker               ",
    "Bag of dicks               ",
    "Bandit                     ",
    "Bangsat                    ",
    "Barbarian                  ",
    "Bastard                    ",
    "Beast                      ",
    "Beetlehead                 ",
    "Beginner                   ",
    "Beldame                    ",
    "Bell-end                   ",
    "Berk                       ",
    "Bespawler                  ",
    "Bimbo                      ",
    "Birdbrain                  ",
    "Bitch                      ",
    "Bitchface                  ",
    "Bitchwad                   ",
    "Bitchzilla                 ",
    "Biznatch                   ",
    "Blackguard                 ",
    "Blaggard                   ",
    "Blockhead                  ",
    "Blubber gut                ",
    "Bluntie                    ",
    "Bogeyman                   ",
    "Bonehead                   ",
    "Booby                      ",
    "Bootlicker                 ",
    "Boozer                     ",
    "Boyfucker                  ",
    "Bozo                       ",
    "Brotherfucker              ",
    "Bruh                       ",
    "Buffoon                    ",
    "Bugger                     ",
    "Bum                        ",
    "Bum-fucker                 ",
    "Bum chum                   ",
    "Burden                     ",
    "Buttfucker                 ",
    "Butthead                   ",
    "Butthole                   ",
    "Buttlicker                 ",
    "Caveman                    ",
    "Chauvinist                 ",
    "Chav                       ",
    "Cheater                    ",
    "Chicken                    ",
    "Chickenfucker              ",
    "Childfucker                ",
    "Chump                      ",
    "Churl                      ",
    "Clown                      ",
    "Cock                       ",
    "Cockboy                    ",
    "Cockfucker                 ",
    "Cockhead                   ",
    "Cockholster                ",
    "Cockmaster                 ",
    "Cockroach                  ",
    "Cocksucker                 ",
    "Cockwomble                 ",
    "Con man                    ",
    "Con merchant               ",
    "Cougar                     ",
    "Country bumpkin            ",
    "Cousinfucker               ",
    "Cow                        ",
    "Coward                     ",
    "Crack whore                ",
    "Crackhead                  ",
    "Craphole                   ",
    "Creep                      ",
    "Cretin                     ",
    "Crook                      ",
    "Cum-licker                 ",
    "Cumstain                   ",
    "Cunt                       ",
    "Cunt fart                  ",
    "Cuntass                    ",
    "Cuntbitch                  ",
    "Cuntlicker                 ",
    "Cuntsucker                 ",
    "Cuntzilla                  ",
    "Daughterfucker             ",
    "Deadhead                   ",
    "Degenerate                 ",
    "Der-brain                  ",
    "Desperado                  ",
    "Devil                      ",
    "Dick                       ",
    "Dick-licker                ",
    "DickLicker                 ",
    "Dick Sniffer               ",
    "Dick weed                  ",
    "Dickbag                    ",
    "Dickbreath                 ",
    "Dickface                   ",
    "Dickfucker                 ",
    "Dickhead                   ",
    "Dicktard                   ",
    "Dimp Damp                  ",
    "Dimwit                     ",
    "Ding-Head                  ",
    "Dinosaur                   ",
    "Dipfuck                    ",
    "Dirtbag                    ",
    "Dirthead                   ",
    "Dodo                       ",
    "Dog                        ",
    "Dogfucker                  ",
    "Dolt                       ",
    "Donkey                     ",
    "Donkeyfucker               ",
    "Doofus                     ",
    "Dope                       ",
    "Dotterel                   ",
    "Douche                     ",
    "Douche bag                 ",
    "Douche canoe               ",
    "Douche nozzle              ",
    "Douchefag                  ",
    "Douchelord                 ",
    "Dracula                    ",
    "Dreamer                    ",
    "Drunkard                   ",
    "Duckfucker                 ",
    "Dumbass                    ",
    "Dumbbell                   ",
    "Dumbo                      ",
    "Dummy                      ",
    "Dunce                      ",
    "Duncebucket                ",
    "Earthworm                  ",
    "Edgelord                   ",
    "Egotist                    ",
    "Envirotard                 ",
    "Eunuch                     ",
    "Faggot                     ",
    "Fagtard                    ",
    "Fagtits                    ",
    "Farmer                     ",
    "Fart                       ",
    "Fatso                      ",
    "Fellow                     ",
    "Fibber                     ",
    "Fink                       ",
    "Fish                       ",
    "Fishwife                   ",
    "Fixer                      ",
    "Flake                      ",
    "Fool                       ",
    "Freak                      ",
    "Fruitcake                  ",
    "Fuck                       ",
    "Fuck noggin                ",
    "Fuck nugget                ",
    "Fuckbait                   ",
    "Fuckbucket                 ",
    "Fucker                     ",
    "Fuckhead                   ",
    "Fucklord                   ",
    "Fucktard                   ",
    "Fucktoy                    ",
    "Fuckweasel                 ",
    "Fugly                      ",
    "Gawk                       ",
    "Geebag                     ",
    "Girl defined               ",
    "Git                        ",
    "Gobshite                   ",
    "Gold digger                ",
    "Goof                       ",
    "Goon                       ",
    "Goose                      ",
    "Gorilla                    ",
    "Greeniac                   ",
    "Grouch                     ",
    "Grumpy                     ",
    "Headass                    ",
    "Helldog                    ",
    "Hilding                    ",
    "Hillbilly                  ",
    "Hippie                     ",
    "Ho                         ",
    "Hoe                        ",
    "Homo                       ",
    "Hooligan                   ",
    "Hooplehead                 ",
    "Horse's ass                ",
    "Horse's necktie            ",
    "Horsefucker                ",
    "Hosebag                    ",
    "Hypocrite                  ",
    "Idiot                      ",
    "Idiotist                   ",
    "Ignoramus                  ",
    "Imbecile                   ",
    "Inbred                     ",
    "Insolent goblin we         ",
    "Intercourser               ",
    "Jackass                    ",
    "Jackwagon                  ",
    "Jelly                      ",
    "Jerk                       ",
    "Joker                      ",
    "Junkie                     ",
    "Keyboard warrior           ",
    "Lamebrain                  ",
    "Landwhale                  ",
    "Lard face                  ",
    "Liar                       ",
    "Libtard                    ",
    "Loser                      ",
    "Low-life                   ",
    "Lunatic                    ",
    "Lunkhead                   ",
    "Lurdane                    ",
    "Mackerel                   ",
    "Madman                     ",
    "Mamzer                     ",
    "Mega Faggot                ",
    "Megabitch                  ",
    "Megadouche                 ",
    "Minx                       ",
    "Missing link               ",
    "Mongoloid                  ",
    "Mongoose                   ",
    "Monkey                     ",
    "Monster                    ",
    "Moron                      ",
    "Motherfucker               ",
    "Mouthbreather              ",
    "Mr.Anger                   ",
    "Mr.Obsessed                ",
    "Mr. Struggle               ",
    "Mr. Talk                   ",
    "Mucky pup                  ",
    "Muppet                     ",
    "Mutant                     ",
    "Mutt                       ",
    "Ne'er-do-well              ",
    "Neanderthal                ",
    "Neckbeard                  ",
    "Nerd                       ",
    "Nerf herder                ",
    "Nimrod                     ",
    "Nincompoop                 ",
    "Ninny                      ",
    "Nitwit                     ",
    "Nobody                     ",
    "Nonce                      ",
    "Noodle                     ",
    "Numbnuts                   ",
    "Numbskull                  ",
    "Numskull                   ",
    "Oaf                        ",
    "Oddball                    ",
    "Ogre                       ",
    "Outlaw                     ",
    "Oxygen Thief               ",
    "Pack                       ",
    "Pain in the ass            ",
    "Pariah                     ",
    "Paul                       ",
    "Peasant                    ",
    "Pencil dick                ",
    "Penis face                 ",
    "Pervert                    ",
    "Pig                        ",
    "Pigfucker                  ",
    "Piggy-wiggy                ",
    "Pillock                    ",
    "Pinhead                    ",
    "Pirate                     ",
    "Pissface                   ",
    "Porno freak                ",
    "Prick                      ",
    "Pseudo-intellectua         ",
    "Pube Flosser               ",
    "Puppet                     ",
    "Pussyfucker                ",
    "Quack                      ",
    "Quat                       ",
    "Queer                      ",
    "Queer bait                 ",
    "Querulant                  ",
    "Rat                        ",
    "Rat-fink                   ",
    "Ratcatcher                 ",
    "Ratfink                    ",
    "Redneck                    ",
    "Reject                     ",
    "Retard                     ",
    "Riff-raff                  ",
    "Roaster                    ",
    "Robot                      ",
    "Rowdy                      ",
    "Rudesby                    ",
    "Ruffian                    ",
    "Sadist                     ",
    "Saprophyte                 ",
    "Sausage-masseuse           ",
    "Scumbag                    ",
    "Scumhead                   ",
    "Scumlord                   ",
    "Scuzzbag                   ",
    "Sewer rat                  ",
    "Shark                      ",
    "Sheepfucker                ",
    "Sheepshagger               ",
    "Shit-eater                 ",
    "Shit-for-Brains            ",
    "Shit stain                 ",
    "Shitass                    ",
    "Shitbucket                 ",
    "Shitehawk                  ",
    "Shithead                   ",
    "Shitneck                   ",
    "Shitnugget                 ",
    "Shitsack                   ",
    "Shitter                    ",
    "Shitweasel                 ",
    "Shyster                    ",
    "Simpleton                  ",
    "Skullfucker                ",
    "Skunk                      ",
    "Skunkfucker                ",
    "Slag                       ",
    "Slave                      ",
    "Sleeze                     ",
    "Sleeze bag                 ",
    "Slob                       ",
    "Slutfucker                 ",
    "Snail                      ",
    "Snake                      ",
    "Snob                       ",
    "Snot                       ",
    "Snotball                   ",
    "Snowflake                  ",
    "Son of a bitch             ",
    "Son of a motherless goat   ",
    "Son of a whore             ",
    "Sphincter                  ",
    "Square                     ",
    "Stinker                    ",
    "Stinkhole                  ",
    "Swindler                   ",
    "Swine                      ",
    "Sycophant                  ",
    "Thief                      ",
    "Thundercunt                ",
    "Toad                       ",
    "Tree hugger                ",
    "Troll                      ",
    "Trollface                  ",
    "Turd                       ",
    "Turdball                   ",
    "Twat                       ",
    "Twatwaffle                 ",
    "Twerp                      ",
    "Twit                       ",
    "Twunt                      ",
    "Ugly ass                   ",
    "Unclefucker                ",
    "Uncultured-swine           ",
    "Vampire                    ",
    "Vandal                     ",
    "Varmint                    ",
    "Vermin                     ",
    "Wacko                      ",
    "Wallflower                 ",
    "Wank stain                 ",
    "Wanker                     ",
    "Weeze Bag                  ",
    "Weirdo                     ",
    "Whore                      ",
    "Whorefucker                ",
    "Whoreson                   ",
    "Windfucker                 ",
    "Windsucker                 ",
    "Wino                       ",
    "Witch                      ",
    "Womanizer                  ",
    "Worm                       ",
    "Wretch                     ",
    "Xenophobe                  ",
    "Yahoo                      ",
    "Yes-man                    ",
    "Zitface                    ",
    "Zoophile                   ",
    "Zounderkite                "
        };
    }
}